### ISSUE TITLE
server.js

### ISSUE THREAD

**Issue by hdrdavies** [kat4/meow#27]
:eggplant::eggplant::eggplant::eggplant::eggplant:
Some refactoring:

Unnecessary comments? 

https://github.com/kat4/meow/blob/master/server.js#L1
https://github.com/kat4/meow/blob/master/server.js#L43
https://github.com/kat4/meow/blob/master/server.js#L48

Unnecessary console.logs?

https://github.com/kat4/meow/blob/master/server.js#L12
https://github.com/kat4/meow/blob/master/server.js#L59

Quite a lot of whitespace going on:

https://github.com/kat4/meow/blob/master/server.js#L63

Arm broken?

https://github.com/kat4/meow/blob/master/server.js#L27

**Comment by Joshua-Ronan-Phillips** [comment]
Kata sorted this
